#!/bin/sh

SCRIPT_PATH="$0"
while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=`readlink "$SCRIPT_PATH"`; done
SCRIPT_PATH="$(dirname $SCRIPT_PATH)"
. "${SCRIPT_PATH}/.config.sh"

COMMIT_MSG_ERR=0
h1 "Running commit-msg hook"
p "You can bypass this with --no-verify (but don't!)"
echo

for module in ${COMMIT_MSG_MODULES}; do
    CURR_MODULE="${COMMIT_MSG_MODULES_PATH}/$module"
    [ ! -e ${CURR_MODULE} ] && continue
    . "${CURR_MODULE}" "$1"
    if [ $? -eq 1 ] ; then
        COMMIT_MSG_ERR=1
    fi
done

if [ ${COMMIT_MSG_ERR} -eq 1 ]; then
	echo "  ${CROSS}${RED} Patience thou must have young padawan!"
else
	echo "  ${CHECK}${GREEN} The force is with you!"
fi

echo ${GREY}
exit ${COMMIT_MSG_ERR}