#!/bin/sh

SCRIPT_PATH="$0"
while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
SCRIPT_PATH="$(dirname "$SCRIPT_PATH")"

# shellcheck disable=SC1090
. "${SCRIPT_PATH}/.githook"
if [ -f "${REPO_PATH}/.githook" ]
then
  # shellcheck disable=SC1090
  . "${REPO_PATH}/.githook"
fi

# shellcheck disable=SC1090
. "${SCRIPT_PATH}/helpers/formatting.sh"

COMMIT_MSG_ERR=0
h1 "commit-msg"
info "You can bypass hooks with ${MAGENTA}--no-verify${GREY} (but don't!)"
info "Rather configure ${GREEN}'repository/.githook'${GREY} to disable rules"

for module in ${commit_msg_modules}; do
    CURR_MODULE="${SCRIPT_PATH}/modules/commit-msg/$module"
    [ ! -e ${CURR_MODULE} ] && continue
    . "${CURR_MODULE}" "$(cat "$1")"
    if [ $? -eq 1 ] ; then
        COMMIT_MSG_ERR=1
    fi
done

echo
if [ ${COMMIT_MSG_ERR} -eq 1 ]; then
	fail "${RED}Patience thou must have young padawan!${GREY}"
else
	pass "${GREEN}The force is with you!${GREY}"
fi

echo "${GREY}"
exit ${COMMIT_MSG_ERR}