#!/bin/sh

SCRIPT_PATH="$0"
while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
SCRIPT_PATH="$(dirname "$SCRIPT_PATH")"

. "${SCRIPT_PATH}/.githook"
if [ -f "${REPO_PATH}/.githook" ]
then
  . "${REPO_PATH}/.githook"
fi

. "${SCRIPT_PATH}/helpers/formatting.sh"
. "${SCRIPT_PATH}/modules/pre-commit/CONFIG.sh"

PRE_COMMIT_ERR=0
h1 "Running pre-commit hook"
p "You can bypass this with --no-verify (but don't!)"
echo

for module in ${PRE_COMMIT_MODULES}; do
    CURR_MODULE="${PRE_COMMIT_MODULES_PATH}/${module}"
    [ ! -e ${CURR_MODULE} ] && continue
    . "${CURR_MODULE}"
    if [ $? -eq 1 ] ; then
        PRE_COMMIT_ERR=1
    fi
done

if [ ${PRE_COMMIT_ERR} -eq 1 ]; then
	echo "  ${CROSS}${RED} Patience thou must have young padawan!"
else
	echo "  ${CHECK}${GREEN} The force is with you!"
fi

echo ${GREY}
exit ${PRE_COMMIT_ERR}