#!/bin/sh

SCRIPT_PATH="$0"
while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
SCRIPT_PATH="$(dirname "$SCRIPT_PATH")"

# shellcheck disable=SC1090
. "${SCRIPT_PATH}/.githook"
if [ -f "${REPO_PATH}/.githook" ]
then
  # shellcheck disable=SC1090
  . "${REPO_PATH}/.githook"
fi

# shellcheck disable=SC1090
. "${SCRIPT_PATH}/helpers/formatting.sh"

PRE_COMMIT_ERR=0
h1 "pre-commit"
info "You can bypass hooks with ${MAGENTA}--no-verify${GREY} (but don't!)"
info "Rather configure ${GREEN}'repository/.githook'${GREY} to disable rules"

# shellcheck disable=SC2154
for module in ${pre_commit_modules}; do
    CURR_MODULE="${SCRIPT_PATH}/modules/pre-commit/${module}"
    [ ! -e "${CURR_MODULE}" ] && continue
    # shellcheck disable=SC1090
    . "${CURR_MODULE}"
    if [ $? -eq 1 ] ; then
        PRE_COMMIT_ERR=1
    fi
done

echo ""
if [ ${PRE_COMMIT_ERR} -eq 1 ]; then
	fail "${RED}Patience thou must have young padawan!${GREY}"
else
	pass "${GREEN}The force is with you!${GREY}"
fi

exit ${PRE_COMMIT_ERR}